# Site settings
author: Derya Kurt 
title: Derya
header-img: img/home-bg.png
email: deryastyle@me.com
copyright_name: Derya Kurt 
description: > # this means to ignore newlines until "baseurl:"
  My journey of learning how to CODE!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  deryastyle7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
